### ISSUE TITLE
Scale bar shows up as "0 m" for the newly uploaded trajectories

### ISSUE THREAD

**Issue by schoinh** [simularium/simularium-engine#20]
## Description

For the 3 newly uploaded trajectories (all but endocytosis and covid), when you load them up the scale bar says "0 m" although when loaded via drag-and-drop the scale bar seems to show the correct length.

## Expected Behavior

The scale bar should show the same length when a trajectory is streamed as when it's loaded via drag and drop.

## Reproduction

1. Go to staging and load "Membrane Wrapping a Nanoparticle" for example
2. See that even after the trajectory finishes loading, the scale bar is at 0 m

## Notes

When I quickly inspected the trajectoryFileInfo that came into simularium-website, I saw that the spatial units values came in with 0 for magnitude and "m" for length? Might be something going astray with the file conversion in the viewer.

**Comment by blairlyons** [comment]
was resolved with https://github.com/simularium/simularium-engine/issues/58
