### ISSUE TITLE
Limit the number of allowed user connections

### ISSUE THREAD

**Issue by EricJIsaac** [simularium/simularium-engine#50]
## Use Case

This will allow us to reject connections, once we exceed a configured limit. A step towards a more scalable and controllable application.

## Acceptance Criteria

After a set number of connections is exceeded, the simularium-engine will not accept the new connection.

## Details

Related to: https://github.com/allen-cell-animated/simularium-engine/issues/49 
Arbitrarily choosing 10,000 connections as the limit

Note: Trajectory pre-processing is the 'competing process' and the variable that most affects what a sensible limit for this is. May be useful to limit that as well (if possible) depending on how much is kept in working memory currently.

**Comment by blairlyons** [comment]
Will revisit with new server implementation
