### ISSUE TITLE
Update EKS Kubernetes to 1.17

### ISSUE THREAD

**Issue by EricJIsaac** [simularium/simularium-engine#52]
## What needs to happen?
Update EKS to 1.17

## Why should we do this?
Support ended for 1.16 last month.
If we encountered a major problem, we may be unable to redeploy.

## When does this need to get done?
Completed, filing issue for project tracking

**Comment by toloudis** [comment]
This is now done mostly by @griffinfujioka but we really need to advance the kubernetes version all the way to current.  Amazon seems to deprecate old versions every 4 months or so.

**Comment by blairlyons** [comment]
tracked in https://github.com/simularium/simularium-engine/issues/72
