### ISSUE TITLE
Update EKS deployment to Kubernetes 1.18

### ISSUE THREAD

**Issue by EricJIsaac** [simularium/simularium-engine#54]
## What needs to happen?
Update the AWS EKS deployment to kubernetes 1.18

## Why should we do this?
Support ends for 1.17 on November 2nd
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Eventually, old versions are removed. 
As a note, AWS seeks to support at least 4 versions, currently there are 6 (1.16 - 1.21)

## When does this need to get done?
December 2021

**Comment by toloudis** [comment]
Really, update to latest kubernetes if possible.

**Comment by blairlyons** [comment]
tracked in https://github.com/simularium/simularium-engine/issues/72
